//
// ActorImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActorImage: Codable {
    public var path: String?
    public var width: Int?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(path: String? = nil, width: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.path = path
        self.width = width
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}
