//
// AddIntroOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddIntroOptions: Codable {
    public var file: Data?

    public init(file: Data? = nil) {
        self.file = file
    }
}
