//
// AddPluginRequestOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddPluginRequestOneOf1: Codable {
    public var path: String

    public init(path: String) {
        self.path = path
    }
}
