//
// AddVideoChannelSync200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoChannelSync200Response: Codable {
    public var videoChannelSync: VideoChannelSync?

    public init(videoChannelSync: VideoChannelSync? = nil) {
        self.videoChannelSync = videoChannelSync
    }
}
