//
// AddVideoPlaylistVideo200ResponseVideoPlaylistElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoPlaylistVideo200ResponseVideoPlaylistElement: Codable {
    public var id: Int?

    public init(id: Int? = nil) {
        self.id = id
    }
}
