//
// AddVideoChannel200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoChannel200Response: Codable {
    public var videoChannel: ApiV1AbusesPost200ResponseAbuse?

    public init(videoChannel: ApiV1AbusesPost200ResponseAbuse? = nil) {
        self.videoChannel = videoChannel
    }
}
