//
// AddVideoPlaylistVideo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoPlaylistVideo200Response: Codable {
    public var videoPlaylistElement: AddVideoPlaylistVideo200ResponseVideoPlaylistElement?

    public init(videoPlaylistElement: AddVideoPlaylistVideo200ResponseVideoPlaylistElement? = nil) {
        self.videoPlaylistElement = videoPlaylistElement
    }
}
