//
// ApiV1VideoChannelsChannelHandleVideoPlaylistsGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1VideoChannelsChannelHandleVideoPlaylistsGet200Response: Codable {
    public var total: Int?
    public var data: [VideoPlaylist]?

    public init(total: Int? = nil, data: [VideoPlaylist]? = nil) {
        self.total = total
        self.data = data
    }
}
