//
// ApiV1VideosIdCommentThreadsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1VideosIdCommentThreadsPostRequest: Codable {
    public var text: Text

    public init(text: Text) {
        self.text = text
    }
}
