//
// ApiV1RunnersJobsGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsGet200Response: Codable {
    public var total: Int?
    public var data: [RunnerJobAdmin]?

    public init(total: Int? = nil, data: [RunnerJobAdmin]? = nil) {
        self.total = total
        self.data = data
    }
}
