//
// ApiV1PluginsNpmNameSettingsPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1PluginsNpmNameSettingsPutRequest: Codable {
    public var settings: [String: Any]?

    public init(settings: [String: Any]? = nil) {
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case settings
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        settings = try container.decodeIfPresent([String: Any].self, forKey: .settings)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let settings = settings {
            try container.encodeIfPresent(try JSONSerialization.data(withJSONObject: settings), forKey: .settings)
        }
    }
}
