//
// ApiV1RunnersJobsRequestPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsRequestPost200Response: Codable {
    public var availableJobs: [ApiV1RunnersJobsRequestPost200ResponseAvailableJobsInner]?

    public init(availableJobs: [ApiV1RunnersJobsRequestPost200ResponseAvailableJobsInner]? = nil) {
        self.availableJobs = availableJobs
    }
}
