//
// ApiV1UsersMeAvatarPickPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1UsersMeAvatarPickPost200Response: Codable {
    public var avatars: [ActorImage]?

    public init(avatars: [ActorImage]? = nil) {
        self.avatars = avatars
    }
}
