//
// ApiV1AbusesPostRequestComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1AbusesPostRequestComment: Codable {
    public var id: Int?

    public init(id: Int? = nil) {
        self.id = id
    }
}
