//
// ApiV1RunnersJobsJobUUIDAcceptPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsJobUUIDAcceptPost200Response: Codable {
    public var job: ApiV1RunnersJobsJobUUIDAcceptPost200ResponseJob?

    public init(job: ApiV1RunnersJobsJobUUIDAcceptPost200ResponseJob? = nil) {
        self.job = job
    }
}
