//
// ApiV1RunnersJobsJobUUIDErrorPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsJobUUIDErrorPostRequest: Codable {
    public var runnerToken: String
    public var jobToken: String
    /// Why the runner failed to process this job
    public var message: String

    public init(runnerToken: String, jobToken: String, message: String) {
        self.runnerToken = runnerToken
        self.jobToken = jobToken
        self.message = message
    }
}
