//
// ApiV1ServerRedundancyHostPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1ServerRedundancyHostPutRequest: Codable {
    /// allow mirroring of the host's local videos
    public var redundancyAllowed: Bool

    public init(redundancyAllowed: Bool) {
        self.redundancyAllowed = redundancyAllowed
    }
}
