//
// ApiV1AbusesPostRequestAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1AbusesPostRequestAccount: Codable {
    /// Account id to report
    public var id: Int?

    public init(id: Int? = nil) {
        self.id = id
    }
}
