//
// ApiV1VideoChannelsChannelHandleBannerPickPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1VideoChannelsChannelHandleBannerPickPost200Response: Codable {
    public var banners: [ActorImage]?

    public init(banners: [ActorImage]? = nil) {
        self.banners = banners
    }
}
