//
// ApiV1RunnersUnregisterPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersUnregisterPostRequest: Codable {
    public var runnerToken: String

    public init(runnerToken: String) {
        self.runnerToken = runnerToken
    }
}
