//
// ApiV1UsersMeVideoPlaylistsVideosExistGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1UsersMeVideoPlaylistsVideosExistGet200Response: Codable {
    public var videoId: [ApiV1UsersMeVideoPlaylistsVideosExistGet200ResponseVideoIdInner]?

    public init(videoId: [ApiV1UsersMeVideoPlaylistsVideosExistGet200ResponseVideoIdInner]? = nil) {
        self.videoId = videoId
    }
}
