//
// ApiV1RunnersJobsJobUUIDSuccessPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsJobUUIDSuccessPostRequest: Codable {
    public var runnerToken: String
    public var jobToken: String
    public var payload: ApiV1RunnersJobsJobUUIDSuccessPostRequestPayload

    public init(runnerToken: String, jobToken: String, payload: ApiV1RunnersJobsJobUUIDSuccessPostRequestPayload) {
        self.runnerToken = runnerToken
        self.jobToken = jobToken
        self.payload = payload
    }
}
