//
// CreateVideoTranscodingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateVideoTranscodingRequest: Codable {
    public enum TranscodingType: String, Codable, CaseIterable {
        case hls = "hls"
        case webVideo = "web-video"
    }
    public var transcodingType: TranscodingType
    /// If the video is stuck in transcoding state, do it anyway
    public var forceTranscoding: Bool? = false

    public init(transcodingType: TranscodingType, forceTranscoding: Bool? = false) {
        self.transcodingType = transcodingType
        self.forceTranscoding = forceTranscoding
    }
}
