//
// CutOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CutOptions: Codable {
    public var start: Int?
    public var end: Int?

    public init(start: Int? = nil, end: Int? = nil) {
        self.start = start
        self.end = end
    }
}
