//
// GetAccounts200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAccounts200Response: Codable {
    public var total: Int?
    public var data: [Account]?

    public init(total: Int? = nil, data: [Account]? = nil) {
        self.total = total
        self.data = data
    }
}
