//
// GetMyAbuses200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetMyAbuses200Response: Codable {
    public var total: Int?
    public var data: [Abuse]?

    public init(total: Int? = nil, data: [Abuse]? = nil) {
        self.total = total
        self.data = data
    }
}
