//
// ListVideoStoryboards200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListVideoStoryboards200Response: Codable {
    public var storyboards: [Storyboard]?

    public init(storyboards: [Storyboard]? = nil) {
        self.storyboards = storyboards
    }
}
