//
// NotificationVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationVideo: Codable {
    public var id: Int?
    public var uuid: Uuid?
    public var name: Name?
    public var channel: ActorInfo?

    public init(id: Int? = nil, uuid: Uuid? = nil, name: Name? = nil, channel: ActorInfo? = nil) {
        self.id = id
        self.uuid = uuid
        self.name = name
        self.channel = channel
    }
}
