//
// PutMirroredVideoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PutMirroredVideoRequest: Codable {
    public var videoId: Int

    public init(videoId: Int) {
        self.videoId = videoId
    }
}
