//
// RegisterUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterUser: Codable {
    /// immutable name of the user, used to find or mention its actor
    public var username: String
    public var password: String
    /// email of the user, used for login or service communications
    public var email: String
    /// editable name of the user, displayed in its representations
    public var displayName: String?
    public var channel: RegisterUserChannel?

    public init(username: String, password: String, email: String, displayName: String? = nil, channel: RegisterUserChannel? = nil) {
        self.username = username
        self.password = password
        self.email = email
        self.displayName = displayName
        self.channel = channel
    }
}
