//
// ResendEmailToVerifyUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResendEmailToVerifyUserRequest: Codable {
    /// User email
    public var email: String

    public init(email: String) {
        self.email = email
    }
}
