//
// RunnerJobStateConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RunnerJobStateConstant: Codable {
    public var id: RunnerJobState?
    public var label: String?

    public init(id: RunnerJobState? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }
}
