//
// ServerStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerStats: Codable {
    public var totalUsers: Double?
    public var totalDailyActiveUsers: Double?
    public var totalWeeklyActiveUsers: Double?
    public var totalMonthlyActiveUsers: Double?
    public var totalLocalVideos: Double?
    /// Total video views made on the instance
    public var totalLocalVideoViews: Double?
    /// Total comments made by local users
    public var totalLocalVideoComments: Double?
    public var totalLocalVideoFilesSize: Double?
    public var totalVideos: Double?
    public var totalVideoComments: Double?
    public var totalLocalVideoChannels: Double?
    public var totalLocalDailyActiveVideoChannels: Double?
    public var totalLocalWeeklyActiveVideoChannels: Double?
    public var totalLocalMonthlyActiveVideoChannels: Double?
    public var totalLocalPlaylists: Double?
    public var totalInstanceFollowers: Double?
    public var totalInstanceFollowing: Double?
    public var videosRedundancy: [ServerStatsVideosRedundancyInner]?
    public var totalActivityPubMessagesProcessed: Double?
    public var totalActivityPubMessagesSuccesses: Double?
    public var totalActivityPubMessagesErrors: Double?
    public var activityPubMessagesProcessedPerSecond: Double?
    public var totalActivityPubMessagesWaiting: Double?

    public init(totalUsers: Double? = nil, totalDailyActiveUsers: Double? = nil, totalWeeklyActiveUsers: Double? = nil, totalMonthlyActiveUsers: Double? = nil, totalLocalVideos: Double? = nil, totalLocalVideoViews: Double? = nil, totalLocalVideoComments: Double? = nil, totalLocalVideoFilesSize: Double? = nil, totalVideos: Double? = nil, totalVideoComments: Double? = nil, totalLocalVideoChannels: Double? = nil, totalLocalDailyActiveVideoChannels: Double? = nil, totalLocalWeeklyActiveVideoChannels: Double? = nil, totalLocalMonthlyActiveVideoChannels: Double? = nil, totalLocalPlaylists: Double? = nil, totalInstanceFollowers: Double? = nil, totalInstanceFollowing: Double? = nil, videosRedundancy: [ServerStatsVideosRedundancyInner]? = nil, totalActivityPubMessagesProcessed: Double? = nil, totalActivityPubMessagesSuccesses: Double? = nil, totalActivityPubMessagesErrors: Double? = nil, activityPubMessagesProcessedPerSecond: Double? = nil, totalActivityPubMessagesWaiting: Double? = nil) {
        self.totalUsers = totalUsers
        self.totalDailyActiveUsers = totalDailyActiveUsers
        self.totalWeeklyActiveUsers = totalWeeklyActiveUsers
        self.totalMonthlyActiveUsers = totalMonthlyActiveUsers
        self.totalLocalVideos = totalLocalVideos
        self.totalLocalVideoViews = totalLocalVideoViews
        self.totalLocalVideoComments = totalLocalVideoComments
        self.totalLocalVideoFilesSize = totalLocalVideoFilesSize
        self.totalVideos = totalVideos
        self.totalVideoComments = totalVideoComments
        self.totalLocalVideoChannels = totalLocalVideoChannels
        self.totalLocalDailyActiveVideoChannels = totalLocalDailyActiveVideoChannels
        self.totalLocalWeeklyActiveVideoChannels = totalLocalWeeklyActiveVideoChannels
        self.totalLocalMonthlyActiveVideoChannels = totalLocalMonthlyActiveVideoChannels
        self.totalLocalPlaylists = totalLocalPlaylists
        self.totalInstanceFollowers = totalInstanceFollowers
        self.totalInstanceFollowing = totalInstanceFollowing
        self.videosRedundancy = videosRedundancy
        self.totalActivityPubMessagesProcessed = totalActivityPubMessagesProcessed
        self.totalActivityPubMessagesSuccesses = totalActivityPubMessagesSuccesses
        self.totalActivityPubMessagesErrors = totalActivityPubMessagesErrors
        self.activityPubMessagesProcessedPerSecond = activityPubMessagesProcessedPerSecond
        self.totalActivityPubMessagesWaiting = totalActivityPubMessagesWaiting
    }
}
