//
// ServerConfigOpenTelemetry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// PeerTube &gt;&#x3D; 6.1 
public struct ServerConfigOpenTelemetry: Codable {
    public var metrics: ServerConfigOpenTelemetryMetrics?

    public init(metrics: ServerConfigOpenTelemetryMetrics? = nil) {
        self.metrics = metrics
    }
}
