//
// ServerConfigViews.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// PeerTube &gt;&#x3D; 6.1 
public struct ServerConfigViews: Codable {
    public var views: ServerConfigViewsViews?

    public init(views: ServerConfigViewsViews? = nil) {
        self.views = views
    }
}
