//
// ServerConfigCustomImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomImport: Codable {
    public var videos: ServerConfigImportVideos?
    public var videoChannelSynchronization: ServerConfigEmail?

    public init(videos: ServerConfigImportVideos? = nil, videoChannelSynchronization: ServerConfigEmail? = nil) {
        self.videos = videos
        self.videoChannelSynchronization = videoChannelSynchronization
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videos
        case videoChannelSynchronization = "video_channel_synchronization"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        videos = try container.decodeIfPresent(ServerConfigImportVideos.self, forKey: .videos)
        videoChannelSynchronization = try container.decodeIfPresent(ServerConfigEmail.self, forKey: .videoChannelSynchronization)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videos, forKey: .videos)
        try container.encodeIfPresent(videoChannelSynchronization, forKey: .videoChannelSynchronization)
    }
}
