//
// ServerConfigViewsViews.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigViewsViews: Codable {
    public var watchingInterval: ServerConfigViewsViewsWatchingInterval?

    public init(watchingInterval: ServerConfigViewsViewsWatchingInterval? = nil) {
        self.watchingInterval = watchingInterval
    }
}
