//
// ServerConfigImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigImport: Codable {
    public var videos: ServerConfigImportVideos?
    public var videoChannelSynchronization: ServerConfigEmail?

    public init(videos: ServerConfigImportVideos? = nil, videoChannelSynchronization: ServerConfigEmail? = nil) {
        self.videos = videos
        self.videoChannelSynchronization = videoChannelSynchronization
    }
}
