//
// ServerConfigCustomTranscodingWebVideos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Web Video specific settings 
public struct ServerConfigCustomTranscodingWebVideos: Codable {
    public var enabled: Bool?

    public init(enabled: Bool? = nil) {
        self.enabled = enabled
    }
}
