//
// ServerConfigTranscoding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigTranscoding: Codable {
    public var hls: ServerConfigEmail?
    public var webVideos: ServerConfigEmail?
    public var enabledResolutions: [Int]?

    public init(hls: ServerConfigEmail? = nil, webVideos: ServerConfigEmail? = nil, enabledResolutions: [Int]? = nil) {
        self.hls = hls
        self.webVideos = webVideos
        self.enabledResolutions = enabledResolutions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hls
        case webVideos = "web_videos"
        case enabledResolutions
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        hls = try container.decodeIfPresent(ServerConfigEmail.self, forKey: .hls)
        webVideos = try container.decodeIfPresent(ServerConfigEmail.self, forKey: .webVideos)
        enabledResolutions = try container.decodeIfPresent([Int].self, forKey: .enabledResolutions)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hls, forKey: .hls)
        try container.encodeIfPresent(webVideos, forKey: .webVideos)
        try container.encodeIfPresent(enabledResolutions, forKey: .enabledResolutions)
    }
}
