//
// Storyboard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Storyboard: Codable {
    public var storyboardPath: String?
    public var totalHeight: Int?
    public var totalWidth: Int?
    public var spriteHeight: Int?
    public var spriteWidth: Int?
    public var spriteDuration: Int?

    public init(storyboardPath: String? = nil, totalHeight: Int? = nil, totalWidth: Int? = nil, spriteHeight: Int? = nil, spriteWidth: Int? = nil, spriteDuration: Int? = nil) {
        self.storyboardPath = storyboardPath
        self.totalHeight = totalHeight
        self.totalWidth = totalWidth
        self.spriteHeight = spriteHeight
        self.spriteWidth = spriteWidth
        self.spriteDuration = spriteDuration
    }
}
