//
// VerifyUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerifyUserRequest: Codable {
    public var verificationString: String
    public var isPendingEmail: Bool?

    public init(verificationString: String, isPendingEmail: Bool? = nil) {
        self.verificationString = verificationString
        self.isPendingEmail = isPendingEmail
    }
}
