//
// VideoConstantNumberLicence.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoConstantNumberLicence: Codable {
    /// licence id of the video (see [/videos/licences](#operation/getLicences))
    public var id: Int?
    public var label: String?

    public init(id: Int? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }
}
