//
// VideosForXMLInnerMediaGroupInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideosForXMLInnerMediaGroupInner: Codable {
    public var href: String?
    public var type: String?
    public var url: String?
    public var fileSize: Int?
    public var framerate: Int?
    public var duration: Int?
    public var height: Int?
    public var lang: String?

    public init(href: String? = nil, type: String? = nil, url: String? = nil, fileSize: Int? = nil, framerate: Int? = nil, duration: Int? = nil, height: Int? = nil, lang: String? = nil) {
        self.href = href
        self.type = type
        self.url = url
        self.fileSize = fileSize
        self.framerate = framerate
        self.duration = duration
        self.height = height
        self.lang = lang
    }
}
