//
// VideoChannelList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannelList: Codable {
    public var total: Int?
    public var data: [VideoChannelListDataInner]?

    public init(total: Int? = nil, data: [VideoChannelListDataInner]? = nil) {
        self.total = total
        self.data = data
    }
}
