//
// VideoImportStateConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoImportStateConstant: Codable {
    public enum Id: Int, Codable, CaseIterable {
        case _1 = 1
        case _2 = 2
        case _3 = 3
    }
    /// The video import state (Pending = `1`, Success = `2`, Failed = `3`)
    public var id: Id?
    public var label: String?

    public init(id: Id? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }
}
