//
// VideoConstantStringLanguage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoConstantStringLanguage: Codable {
    /// language id of the video (see [/videos/languages](#operation/getLanguages))
    public var id: String?
    public var label: String?

    public init(id: String? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }
}
