//
// VideosForXMLInnerMediaCommunity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// see [media:community](https://www.rssboard.org/media-rss#media-community) (MRSS) 
public struct VideosForXMLInnerMediaCommunity: Codable {
    public var mediastatistics: VideosForXMLInnerMediaCommunityMediaStatistics?

    public init(mediastatistics: VideosForXMLInnerMediaCommunityMediaStatistics? = nil) {
        self.mediastatistics = mediastatistics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediastatistics = "media:statistics"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        mediastatistics = try container.decodeIfPresent(VideosForXMLInnerMediaCommunityMediaStatistics.self, forKey: .mediastatistics)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediastatistics, forKey: .mediastatistics)
    }
}
