//
// VideoChannelSyncList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannelSyncList: Codable {
    public var total: Int?
    public var data: [VideoChannelSync]?

    public init(total: Int? = nil, data: [VideoChannelSync]? = nil) {
        self.total = total
        self.data = data
    }
}
