//
// VideoComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoComment: Codable {
    public var id: Int?
    public var url: String?
    /// Text of the comment
    public var text: String?
    public var threadId: Int?
    public var inReplyToCommentId: Int?
    public var videoId: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var deletedAt: Date?
    public var isDeleted: Bool? = false
    public var totalRepliesFromVideoAuthor: Int?
    public var totalReplies: Int?
    public var account: Account?

    public init(id: Int? = nil, url: String? = nil, text: String? = nil, threadId: Int? = nil, inReplyToCommentId: Int? = nil, videoId: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, deletedAt: Date? = nil, isDeleted: Bool? = false, totalRepliesFromVideoAuthor: Int? = nil, totalReplies: Int? = nil, account: Account? = nil) {
        self.id = id
        self.url = url
        self.text = text
        self.threadId = threadId
        self.inReplyToCommentId = inReplyToCommentId
        self.videoId = videoId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.deletedAt = deletedAt
        self.isDeleted = isDeleted
        self.totalRepliesFromVideoAuthor = totalRepliesFromVideoAuthor
        self.totalReplies = totalReplies
        self.account = account
    }
}
