//
// VideosForXMLInnerMediaCommunityMediaStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideosForXMLInnerMediaCommunityMediaStatistics: Codable {
    public var views: Int?

    public init(views: Int? = nil) {
        self.views = views
    }
}
