//
// VideoChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannel: Codable {
    public var id: Int?
    public var url: String?
    /// immutable name of the user, used to find or mention its actor
    public var name: String?
    /// server on which the actor is resident
    public var host: String?
    /// whether this actor's host allows redundancy of its videos
    public var hostRedundancyAllowed: Bool?
    /// number of actors subscribed to by this actor, as seen by this instance
    public var followingCount: Int?
    /// number of followers of this actor, as seen by this instance
    public var followersCount: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    /// editable name of the channel, displayed in its representations
    public var displayName: String?
    public var description: String?
    /// text shown by default on all videos of this channel, to tell the audience how to support it
    public var support: String?
    public var isLocal: Bool?
    public var banners: [ActorImage]?
    public var ownerAccount: VideoChannelAllOfOwnerAccount?

    public init(id: Int? = nil, url: String? = nil, name: String? = nil, host: String? = nil, hostRedundancyAllowed: Bool? = nil, followingCount: Int? = nil, followersCount: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, displayName: String? = nil, description: String? = nil, support: String? = nil, isLocal: Bool? = nil, banners: [ActorImage]? = nil, ownerAccount: VideoChannelAllOfOwnerAccount? = nil) {
        self.id = id
        self.url = url
        self.name = name
        self.host = host
        self.hostRedundancyAllowed = hostRedundancyAllowed
        self.followingCount = followingCount
        self.followersCount = followersCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.displayName = displayName
        self.description = description
        self.support = support
        self.isLocal = isLocal
        self.banners = banners
        self.ownerAccount = ownerAccount
    }
}
