//
// VideosForXMLInnerMediaEmbed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideosForXMLInnerMediaEmbed: Codable {
    /// video embed path, relative to the canonical URL domain (MRSS)
    public var url: String?

    public init(url: String? = nil) {
        self.url = url
    }
}
