//
// VideoTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoTokenResponse: Codable {
    public var files: VideoTokenResponseFiles?

    public init(files: VideoTokenResponseFiles? = nil) {
        self.files = files
    }
}
