//
// VideoConstantNumberCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoConstantNumberCategory: Codable {
    /// category id of the video (see [/videos/categories](#operation/getCategories))
    public var id: Int?
    public var label: String?

    public init(id: Int? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }
}
