//
// VideoSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoSource: Codable {
    public var filename: String?
    public var createdAt: Date?

    public init(filename: String? = nil, createdAt: Date? = nil) {
        self.filename = filename
        self.createdAt = createdAt
    }
}
