//
// VideoStatsTimeserieDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStatsTimeserieDataInner: Codable {
    public var date: String?
    public var value: Double?

    public init(date: String? = nil, value: Double? = nil) {
        self.date = date
        self.value = value
    }
}
