//
// VideoPasswordList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoPasswordList: Codable {
    public var total: Int?
    public var data: [VideoPassword]?

    public init(total: Int? = nil, data: [VideoPassword]? = nil) {
        self.total = total
        self.data = data
    }
}
