//
// VODAudioMergeTranscoding1Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VODAudioMergeTranscoding1Input: Codable {
    public var audioFileUrl: String?
    public var previewFileUrl: String?

    public init(audioFileUrl: String? = nil, previewFileUrl: String? = nil) {
        self.audioFileUrl = audioFileUrl
        self.previewFileUrl = previewFileUrl
    }
}
