//
// VODWebVideoTranscoding1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VODWebVideoTranscoding1Output: Codable {
    public var resolution: Double?
    public var fps: Double?

    public init(resolution: Double? = nil, fps: Double? = nil) {
        self.resolution = resolution
        self.fps = fps
    }
}
