//
// VODWebVideoTranscoding1Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VODWebVideoTranscoding1Input: Codable {
    public var videoFileUrl: String?

    public init(videoFileUrl: String? = nil) {
        self.videoFileUrl = videoFileUrl
    }
}
