//
// VideoImportsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import Combine
import OpenAPITransport


open class VideoImportsAPI {
    private let transport: OpenAPITransport
    public var encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(OpenISO8601DateFormatter())
        return encoder
    }()
    public var decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(OpenISO8601DateFormatter())
        return decoder
    }()
    public var baseURL = URL(string: "https://peertube2.cpy.re")

    public init(_ transport: OpenAPITransport) {
        self.transport = transport
    }


    /// Cancel video import
    /// - POST /api/v1/videos/imports/{id}/cancel
    /// - Cancel a pending video import
    /// - OAuth:
    /// - type: oauth2
    /// - name: OAuth2
    /// - parameter id: (path) Entity id 
    /// - returns: AnyPublisher<Void, Error> 
    open func apiV1VideosImportsIdCancelPost(id: Int) -> AnyPublisher<Void, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var path = "/api/v1/videos/imports/{id}/cancel"
                path = path.replacingOccurrences(of: "{id}", with: "\(id)")
                let url = baseURL.appendingPathComponent(path)
                let components = URLComponents(url: url, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Void, Error> in 
            return self.transport.send(request: request)
                .tryMap { response in
                    return ()
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }


    /// Delete video import
    /// - DELETE /api/v1/videos/imports/{id}
    /// - Delete ended video import
    /// - OAuth:
    /// - type: oauth2
    /// - name: OAuth2
    /// - parameter id: (path) Entity id 
    /// - returns: AnyPublisher<Void, Error> 
    open func apiV1VideosImportsIdDelete(id: Int) -> AnyPublisher<Void, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var path = "/api/v1/videos/imports/{id}"
                path = path.replacingOccurrences(of: "{id}", with: "\(id)")
                let url = baseURL.appendingPathComponent(path)
                let components = URLComponents(url: url, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "DELETE"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Void, Error> in 
            return self.transport.send(request: request)
                .tryMap { response in
                    return ()
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum ImportVideoError: Error, CustomStringConvertible {
        // `magnetUri` or `targetUrl` or a torrent file missing
        case code400Error
        // video didn't pass pre-import filter
        case code403Error
        // HTTP or Torrent/magnetURI import not enabled
        case code409Error

        public var description: String {
            switch self {
            case .code400Error:
                return "ImportVideoError: `magnetUri` or `targetUrl` or a torrent file missing"
            case .code403Error:
                return "ImportVideoError: video didn't pass pre-import filter"
            case .code409Error:
                return "ImportVideoError: HTTP or Torrent/magnetURI import not enabled"
            }
        }
    }

    /// Import a video
    /// - POST /api/v1/videos/imports
    /// - Import a torrent or magnetURI or HTTP resource (if enabled by the instance administrator)
    /// - OAuth:
    /// - type: oauth2
    /// - name: OAuth2
    /// - parameter name: (form) Video name 
    /// - parameter channelId: (form) Channel id that will contain this video 
    /// - parameter privacy: (form)  (optional)
    /// - parameter category: (form) category id of the video (see [/videos/categories](#operation/getCategories)) (optional)
    /// - parameter licence: (form) licence id of the video (see [/videos/licences](#operation/getLicences)) (optional)
    /// - parameter language: (form) language id of the video (see [/videos/languages](#operation/getLanguages)) (optional)
    /// - parameter description: (form) Video description (optional)
    /// - parameter waitTranscoding: (form) Whether or not we wait transcoding before publish the video (optional)
    /// - parameter support: (form) A text tell the audience how to support the video creator (optional)
    /// - parameter nsfw: (form) Whether or not this video contains sensitive content (optional)
    /// - parameter tags: (form) Video tags (maximum 5 tags each between 2 and 30 characters) (optional)
    /// - parameter commentsEnabled: (form) Enable or disable comments for this video (optional)
    /// - parameter downloadEnabled: (form) Enable or disable downloading for this video (optional)
    /// - parameter originallyPublishedAt: (form) Date when the content was originally published (optional)
    /// - parameter scheduleUpdate: (form)  (optional)
    /// - parameter thumbnailfile: (form) Video thumbnail file (optional)
    /// - parameter previewfile: (form) Video preview file (optional)
    /// - parameter videoPasswords: (form)  (optional)
    /// - returns: AnyPublisher<VideoUploadResponse, Error> 
    open func importVideo(name: String, channelId: Int, privacy: VideoPrivacySet? = nil, category: Int? = nil, licence: Int? = nil, language: String? = nil, description: String? = nil, waitTranscoding: Bool? = nil, support: String? = nil, nsfw: Bool? = nil, tags: [String]? = nil, commentsEnabled: Bool? = nil, downloadEnabled: Bool? = nil, originallyPublishedAt: Date? = nil, scheduleUpdate: VideoScheduledUpdate? = nil, thumbnailfile: Data? = nil, previewfile: Data? = nil, videoPasswords: [String]? = nil) -> AnyPublisher<VideoUploadResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let path = "/api/v1/videos/imports"
                let url = baseURL.appendingPathComponent(path)
                let components = URLComponents(url: url, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                let multipartBoundary = String(format: "Boundary+%08X%08X", arc4random(), arc4random())
                var multipartData = Data()
				let nameHeader = "--\(multipartBoundary)\r\n"
				    .appending("Content-Disposition:form-data; name=\"name\"\r\n")
				    .appending("\r\n")
				multipartData.append(nameHeader.data(using: .utf8) ?? Data())
				multipartData.append(name.data(using: .utf8) ?? Data())
				multipartData.append("\r\n".data(using: .utf8) ?? Data())

				let channelIdHeader = "--\(multipartBoundary)\r\n"
				    .appending("Content-Disposition:form-data; name=\"channelId\"\r\n")
				    .appending("\r\n")
				multipartData.append(channelIdHeader.data(using: .utf8) ?? Data())
				multipartData.append()
				multipartData.append("\r\n".data(using: .utf8) ?? Data())

				if let privacy = privacy {
					let privacyHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"privacy\"\r\n")
					    .appending("\r\n")
					multipartData.append(privacyHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let category = category {
					let categoryHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"category\"\r\n")
					    .appending("\r\n")
					multipartData.append(categoryHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let licence = licence {
					let licenceHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"licence\"\r\n")
					    .appending("\r\n")
					multipartData.append(licenceHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let language = language {
					let languageHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"language\"\r\n")
					    .appending("\r\n")
					multipartData.append(languageHeader.data(using: .utf8) ?? Data())
					multipartData.append(language.data(using: .utf8) ?? Data())
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let description = description {
					let descriptionHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"description\"\r\n")
					    .appending("\r\n")
					multipartData.append(descriptionHeader.data(using: .utf8) ?? Data())
					multipartData.append(description.data(using: .utf8) ?? Data())
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let waitTranscoding = waitTranscoding {
					let waitTranscodingHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"waitTranscoding\"\r\n")
					    .appending("\r\n")
					multipartData.append(waitTranscodingHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let support = support {
					let supportHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"support\"\r\n")
					    .appending("\r\n")
					multipartData.append(supportHeader.data(using: .utf8) ?? Data())
					multipartData.append(support.data(using: .utf8) ?? Data())
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let nsfw = nsfw {
					let nsfwHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"nsfw\"\r\n")
					    .appending("\r\n")
					multipartData.append(nsfwHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let tags = tags {
					let tagsHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"tags\"\r\n")
					    .appending("\r\n")
					multipartData.append(tagsHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let commentsEnabled = commentsEnabled {
					let commentsEnabledHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"commentsEnabled\"\r\n")
					    .appending("\r\n")
					multipartData.append(commentsEnabledHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let downloadEnabled = downloadEnabled {
					let downloadEnabledHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"downloadEnabled\"\r\n")
					    .appending("\r\n")
					multipartData.append(downloadEnabledHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let originallyPublishedAt = originallyPublishedAt {
					let originallyPublishedAtHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"originallyPublishedAt\"\r\n")
					    .appending("\r\n")
					multipartData.append(originallyPublishedAtHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let scheduleUpdate = scheduleUpdate {
					let scheduleUpdateHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"scheduleUpdate\"\r\n")
					    .appending("\r\n")
					multipartData.append(scheduleUpdateHeader.data(using: .utf8) ?? Data())
					multipartData.append(try self.encoder.encode(scheduleUpdate))
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let thumbnailfile = thumbnailfile {
					let thumbnailfileHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"thumbnailfile\"; filename=\"thumbnailfile\"\r\n")
					    .appending("Content-Type: image/jpeg\r\n")
					    .appending("\r\n")
					multipartData.append(thumbnailfileHeader.data(using: .utf8) ?? Data())
					multipartData.append(thumbnailfile)
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let previewfile = previewfile {
					let previewfileHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"previewfile\"; filename=\"previewfile\"\r\n")
					    .appending("Content-Type: image/jpeg\r\n")
					    .appending("\r\n")
					multipartData.append(previewfileHeader.data(using: .utf8) ?? Data())
					multipartData.append(previewfile)
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				if let videoPasswords = videoPasswords {
					let videoPasswordsHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"videoPasswords\"\r\n")
					    .appending("\r\n")
					multipartData.append(videoPasswordsHeader.data(using: .utf8) ?? Data())
					multipartData.append()
				}

                multipartData.append("\r\n--\(multipartBoundary)--\r\n".data(using: .utf8) ?? Data())
                request.httpBody = multipartData
                request.setValue("\(multipartData.count)", forHTTPHeaderField: "Content-Length")
                request.setValue("multipart/form-data; boundary=\(multipartBoundary)", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<VideoUploadResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        return ImportVideoError.code400Error
                    }
                    if transportError.statusCode == 403 {
                        return ImportVideoError.code403Error
                    }
                    if transportError.statusCode == 409 {
                        return ImportVideoError.code409Error
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(VideoUploadResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }
}
